FAST_RCNN:
  ROI_BOX_HEAD: head_builder.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
FPN:
  FPN_ON: true
  MULTILEVEL_ROIS: true
  MULTILEVEL_RPN: true
MODEL:
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  TYPE: fast_rcnn
NUM_GPUS: 8
OUTPUT_DIR: .
SOLVER:
  BASE_LR: 0.02
  GAMMA: 0.1
  LR_POLICY: steps_with_decay
  MAX_ITER: 90000
  STEPS:
  - 0
  - 60000
  - 80000
  WEIGHT_DECAY: 0.0001
TEST:
  DATASETS: ('coco_2014_minival',)
  MAX_SIZE: 1333
  NMS: 0.5
  PROPOSAL_FILES: ('https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_minival/generalized_rcnn/rpn_proposals.pkl',)
  PROPOSAL_LIMIT: 1000
  SCALE: 800
TRAIN:
  BATCH_SIZE_PER_IM: 512
  DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')
  MAX_SIZE: 1333
  PROPOSAL_FILES: ('https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_train/generalized_rcnn/rpn_proposals.pkl',
    'https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_valminusminival/generalized_rcnn/rpn_proposals.pkl')
  SCALES: (800,)
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
USE_NCCL: false
